### ISSUE TITLE
What is IC task?🫶

### ISSUE THREAD

**Issue by callmewenhao** [EmbeddedML-EDAGroup/multi-objective-nas#3]
Hi bro, i read your papaer, and there is a sentence "Table I summarizes the deployment results on the NUCLEO-H743ZI2 for the IC and VWW benchmarks. ", i know what is VWW, but what is IC benchmarks? thanks!

**Comment by matteorisso** [comment]
Dear Wenhao, IC stands for Image Classification. In particular, you can refer to the generic code as it is implemented in our [pytorch-benchmarks](https://github.com/eml-eda/pytorch-benchmarks/tree/main) library.

Best,
Matteo
